<?php
/**
 * Forkel OpenGraph
 *
 * @category    Forkel
 * @package     Forkel_OpenGraph
 * @copyright   Copyright (c) 2015 Tobias Forkel (http://www.tobiasforkel.de)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
//<![CDATA[

jQuery(document).ready(function($) {

    var t,x;

    // Form
    var form = '#forkel_opengraph';
    var form_key = $(form + ' input[name="form_key"]').val();

    // AJAX
    var url = $(form + ' input[name="ajax_url"]').val();
    var fields = {'title':'', 'description':'', 'url':'', 'image':''};

    // Source
    var source = $(form + ' textarea[name="comment"]');

    // Image
    var img = $('<img style="max-width: 535px;" />');
    img.appendTo($('#container'));

    source.keyup(function(e)
    {
        if (x) {x.abort()}
        clearTimeout(t);

        var comment = this.value;

        t = setTimeout(function(e)
        {
            if (comment.indexOf('://') == -1)
            {
                $(form + ' .success').addClass('hidden').removeClass('success');
            }
            else
            {
                // Params for AJAX post request
                var params = {'form_key': form_key, 'comment': comment};

                $.ajax({
                    type: 'POST',
                    url: url,
                    data: params,
                    success: function(response, status, xhr)
                    {
                        var header = xhr.getResponseHeader('content-type') || '';

                        // Check the response header and status
                        if (header.indexOf('json') > -1 && status === 'success')
                        {
                            var image = (typeof response['image'] !== 'undefined') ? response['image'] : '';

                            // Show hidden fields
                            $(form + ' .hidden').addClass('success').removeClass('hidden');

                            // Update values from response
                            $.each(fields, function( key, value ){
                                $('#' + key).val(response[key])
                            });

                            // Update image with a new src
                            img.attr('src', image);
                        }
                    }
                });
            }

        }, 700);
    });

});

//]]>
</script>
