<?php
/**
 * Forkel OpenGraph
 *
 * @category    Forkel
 * @package     Forkel_OpenGraph
 * @copyright   Copyright (c) 2015 Tobias Forkel (http://www.tobiasforkel.de)
 * @license     http://opensource.org/licenses/osl-3.0.php Open Software License (OSL 3.0)
 */
?>

<script type="text/javascript">
//<![CDATA[

jQuery(document).ready(function($) {

    var t,x;

    $('.forkel_opengraph_ajax').keyup(function(e)
    {
        if (x) {x.abort()}
        clearTimeout(t);

        var comment = this.value;

        t = setTimeout(function(e)
        {
            if (comment.indexOf('://') != -1)
            {
                // Set form key for correct post to controller action
                var form_key = $("input[name='form_key']").val();

                // Set url to the controller action
                var url = "<?php echo $this->getUrl('adminhtml/forkel_opengraph_entity/ajax'); ?>";

                // Set params for AJAX post request
                var params = {
                    'form_key': form_key,
                    'comment': comment
                };

                // Execute the AJAX request
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: params,
                    success: function(response)
                    {
                        if (typeof response === 'object')
                        {
                            // Reset fields
                            $.each({'title':'', 'description':'', 'url':'', 'image':''}, function( key, value ){
                                $('#' + key).val(value);
                            });

                            $.each(response, function( key, value ){
                                $('#' + key).val(value)
                            });
                        }
                    }
                });
            }

        }, 700);
    });

});

//]]>
</script>

